// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBI5jjdNVAtufFG1_0Nm79RSqHMFZxmspY',
    appId: '1:450340968545:web:6d6b6bfdca74df90d07220',
    messagingSenderId: '450340968545',
    projectId: 'university-management-sy-352bf',
    authDomain: 'university-management-sy-352bf.firebaseapp.com',
    databaseURL: 'https://university-management-sy-352bf-default-rtdb.firebaseio.com',
    storageBucket: 'university-management-sy-352bf.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBhpCU7xHaOhEp3XM9h_9mc8baa2IFbZ7Y',
    appId: '1:450340968545:android:854c6715e5024431d07220',
    messagingSenderId: '450340968545',
    projectId: 'university-management-sy-352bf',
    databaseURL: 'https://university-management-sy-352bf-default-rtdb.firebaseio.com',
    storageBucket: 'university-management-sy-352bf.appspot.com',
  );

}